version: "3.4"

services:
  asr-webservice:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: ./.env
        required: false
    environment:
      - ASR_ENGINE=gigaam
      - ASR_MODEL=v1_rnnt
      - ASR_REQUEST_LOGGING=true
      #- ASR_MODEL=v3_e2e_rnnt
      #- ASR_ENGINE=whisperx
      #- ASR_MODEL=tiny
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app/app
      - cache-whisper:/root/.cache

  client:
    build:
      context: ./client
    profiles:
      - client
    depends_on:
      - asr-webservice
    environment:
      - ASR_CLIENT_SERVER_URL=http://asr-webservice:9000
      - ASR_CLIENT_AUDIO_DIR=/audio
    volumes:
      - ./audio:/audio

volumes:
  cache-whisper:
