version: "3.4"

services:
  whisper-asr-webservice:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: ./.env
        required: false
    environment:
      - ASR_MODEL=base
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app/app
      - cache-whisper:/root/.cache

  client:
    build:
      context: ./client
    profiles:
      - client
    depends_on:
      - whisper-asr-webservice
    environment:
      - ASR_CLIENT_SERVER_URL=http://whisper-asr-webservice:9000
      - ASR_CLIENT_AUDIO_DIR=/audio
    volumes:
      - ./audio:/audio

volumes:
  cache-whisper:
