version: "3.4"

services:
  asr-webservice-gpu:
    image: asr-webservice:latest
    build:
      context: .
      dockerfile: Dockerfile.gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    env_file:
      - path: ./.env
        required: false
    environment:
      - ASR_ENGINE=gigaam
      - ASR_MODEL=v3_ctc
      - ASR_REQUEST_LOGGING=true
      #- ASR_MODEL=v3_e2e_rnnt
      #- ASR_ENGINE=whisperx
      #- ASR_MODEL=tiny
      - HF_TOKEN=${HF_TOKEN}
      - HF_HUB_DISABLE_TELEMETRY=true
      - HF_HUB_OFFLINE=true
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app/app
      - cache-whisper:/root/.cache

  client:
    build:
      context: ./client
    profiles:
      - client
    depends_on:
      - asr-webservice-gpu
    environment:
      - ASR_CLIENT_SERVER_URL=http://asr-webservice-gpu:9000
      - ASR_CLIENT_AUDIO_DIR=/audio
      - HF_TOKEN=${HF_TOKEN}
      - HF_HUB_DISABLE_TELEMETRY=true
      - HF_HUB_OFFLINE=true
    volumes:
      - ./audio:/audio

volumes:
  cache-whisper:
