version: "3.4"

services:
  whisper-asr-webservice-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    env_file:
      - path: ./.env
        required: false
    environment:
      - ASR_MODEL=base
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app/app
      - cache-whisper:/root/.cache

  client:
    build:
      context: ./client
    profiles:
      - client
    depends_on:
      - whisper-asr-webservice-gpu
    environment:
      - ASR_CLIENT_SERVER_URL=http://whisper-asr-webservice-gpu:9000
      - ASR_CLIENT_AUDIO_DIR=/audio
      - ASR_CLIENT_OUTPUT_DIR=/output
    volumes:
      - ./audio:/audio:ro
      - ./client/output:/output

volumes:
  cache-whisper:
